# **Week #9-10 - CASE : DVD RENTAL ETL**

Intro to Data Engineering Course - Sekolah Engineer - Pacmann Academy

In [1]:
%pip install tabulate
import pandas as pd
from tabulate import tabulate
import warnings 
  
warnings.filterwarnings('ignore')

Requirement already satisfied: tabulate in c:\users\syari\appdata\local\programs\python\python312\lib\site-packages (0.9.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 1. Data Source

### 1.1. Data Source I : API

- Data `city` : https://raw.githubusercontent.com/rahilpacmann/case-data-wrangling-api/main/city.csv

In [2]:
city_raw = "https://raw.githubusercontent.com/rahilpacmann/case-data-wrangling-api/main/city.csv"

### 1.2. Data Source II : API

- Data `country` : https://raw.githubusercontent.com/rahilpacmann/case-data-wrangling-api/main/country.csv

In [3]:
country_raw = "https://raw.githubusercontent.com/rahilpacmann/case-data-wrangling-api/main/country.csv"

### 1.3. Data Source III : Database

- ***NOTES : Pastikan anda sudah mempersiapkan Data Source 3. Silahkan lihat "Live Class Preparation" pada Chapter 9***

- Jika sudah mempersiapkan data source 3 buat koneksi ke database tersebut.
    - dbname = "dvdrental"
    - user = "postgres"
    - password = "qwerty123"
    - host = "localhost"
    - port = "5433"

In [11]:
# Your code here
# Buat koneksi ke database
import psycopg2
from sqlalchemy import create_engine


dbname = "dvdrental"
user = "postgres"
password = "qwerty123"
host = "localhost"
port = "5433"

# Membuat koneksi ke database
engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{dbname}')

### 1.4. Requirements (JSON)

- Requirements :
    - https://rahilpacmann.github.io/case-data-wrangling-api/requirements_table.json
- Requirements tersebut meliputi :
    - Nama tabel
    - Nama kolom pada setiap tabel
    - Tipe data pada setiap tabel

In [5]:
requirements_table_url = 'https://rahilpacmann.github.io/case-data-wrangling-api/requirements_table.json'

- Load Json

In [6]:
# Your code here
import urllib.request, json 

with urllib.request.urlopen(requirements_table_url) as url:
    requirements_table = json.load(url)
    
print(requirements_table)

{'actor': [{'column_name': 'actor_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'first_name', 'data_type': 'object'}, {'column_name': 'last_name', 'data_type': 'object'}], 'store': [{'column_name': 'store_id', 'data_type': 'int64'}, {'column_name': 'manager_staff_id', 'data_type': 'int64'}, {'column_name': 'address_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}], 'address': [{'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'city_id', 'data_type': 'int64'}, {'column_name': 'address_id', 'data_type': 'int64'}, {'column_name': 'district', 'data_type': 'object'}, {'column_name': 'phone', 'data_type': 'object'}, {'column_name': 'postal_code', 'data_type': 'object'}, {'column_name': 'address', 'data_type': 'object'}, {'column_name': 'address2', 'data_type': 'object'}], 'category': [{'column_name': 'category_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'name', 'data_type': 'object'}], 'city': [{'column_name': 'city_id', 'data_type': 'int64'}, {'column_name': 'country_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'city', 'data_type': 'object'}], 'country': [{'column_name': 'country_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'country', 'data_type': 'object'}], 'customer': [{'column_name': 'active', 'data_type': 'int64'}, {'column_name': 'store_id', 'data_type': 'int64'}, {'column_name': 'create_date', 'data_type': 'datetime64[ns]'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'customer_id', 'data_type': 'int64'}, {'column_name': 'address_id', 'data_type': 'int64'}, {'column_name': 'activebool', 'data_type': 'bool'}, {'column_name': 'first_name', 'data_type': 'object'}, {'column_name': 'last_name', 'data_type': 'object'}, {'column_name': 'email', 'data_type': 'object'}], 'film_actor': [{'column_name': 'actor_id', 'data_type': 'int64'}, {'column_name': 'film_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}], 'film_category': [{'column_name': 'film_id', 'data_type': 'int64'}, {'column_name': 'category_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}], 'inventory': [{'column_name': 'inventory_id', 'data_type': 'int64'}, {'column_name': 'film_id', 'data_type': 'int64'}, {'column_name': 'store_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}], 'language': [{'column_name': 'language_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'name', 'data_type': 'object'}], 'rental': [{'column_name': 'rental_id', 'data_type': 'int64'}, {'column_name': 'rental_date', 'data_type': 'datetime64[ns]'}, {'column_name': 'inventory_id', 'data_type': 'int64'}, {'column_name': 'customer_id', 'data_type': 'int64'}, {'column_name': 'return_date', 'data_type': 'datetime64[ns]'}, {'column_name': 'staff_id', 'data_type': 'int64'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}], 'staff': [{'column_name': 'picture', 'data_type': 'object'}, {'column_name': 'address_id', 'data_type': 'int64'}, {'column_name': 'store_id', 'data_type': 'int64'}, {'column_name': 'active', 'data_type': 'bool'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'staff_id', 'data_type': 'int64'}, {'column_name': 'first_name', 'data_type': 'object'}, {'column_name': 'last_name', 'data_type': 'object'}, {'column_name': 'password', 'data_type': 'object'}, {'column_name': 'email', 'data_type': 'object'}, {'column_name': 'username', 'data_type': 'object'}], 'payment': [{'column_name': 'payment_id', 'data_type': 'int64'}, {'column_name': 'customer_id', 'data_type': 'int64'}, {'column_name': 'staff_id', 'data_type': 'int64'}, {'column_name': 'rental_id', 'data_type': 'int64'}, {'column_name': 'amount', 'data_type': 'float64'}, {'column_name': 'payment_date', 'data_type': 'datetime64[ns]'}], 'film': [{'column_name': 'fulltext', 'data_type': 'object'}, {'column_name': 'rating', 'data_type': 'object'}, {'column_name': 'last_update', 'data_type': 'datetime64[ns]'}, {'column_name': 'film_id', 'data_type': 'int64'}, {'column_name': 'release_year', 'data_type': 'int64'}, {'column_name': 'language_id', 'data_type': 'int64'}, {'column_name': 'rental_duration', 'data_type': 'int64'}, {'column_name': 'rental_rate', 'data_type': 'float64'}, {'column_name': 'length', 'data_type': 'int64'}, {'column_name': 'replacement_cost', 'data_type': 'float64'}, {'column_name': 'title', 'data_type': 'object'}, {'column_name': 'description', 'data_type': 'object'}, {'column_name': 'special_features', 'data_type': 'object'}]}

## 2. Extract

### 2.1. Extract From Data Source I

- Lakukan ekstrak data dari Data Source I
- Simpan dataframenya dengan nama `city_df`

In [7]:
# Your code here
# Read data
...
city_df = pd.read_csv(city_raw)
# Tampilkan 5 data teratas
...
city_df.head(5)

   city_id                city               country
0        1  A Corua (La Corua)                 Spain
1        2                Abha          Saudi Arabia
2        3           Abu Dhabi  United Arab Emirates
3        4                Acua                Mexico
4        5               Adana                Turkey

### 2.2. Extract From Data Source II

- Lakukan ekstrak data dari Data Source II
- Simpan dataframenya dengan nama `country_df`

In [8]:
# Your code here
# Read data
...
country_df = pd.read_csv(country_raw)
# Tampilkan 5 data teratas
...

country_df.head()

          country          last_update
0     Afghanistan  2006-02-15 09:44:00
1         Algeria  2006-02-15 09:44:00
2  American Samoa  2006-02-15 09:44:00
3          Angola  2006-02-15 09:44:00
4        Anguilla  2006-02-15 09:44:00

### 2.3. Extract From Data Source III

- Buatlah function untuk mendapatkan tabel pada database
- Parameter :
    - nama tabel
    - engine koneksi ke database
- Return : dataframe

In [9]:
# Your code here
# Buat fungsi untuk mendapatkan tabel pada database
...
def get_table_data(name, eng):
    try:
        query = f'SELECT * FROM {name}'
        df = pd.read_sql(query, eng)

        return df
    except Exception as e:
        print(f"error = {e}")

        return pd.DataFrame()

- Buat masing-masing dataframe untuk setiap table tersebut

In [12]:
actor_df = get_table_data('actor', engine)
store_df = get_table_data('store', engine)
address_df = get_table_data('address', engine)
category_df = get_table_data('category', engine)
customer_df = get_table_data('customer', engine)
film_actor_df = get_table_data('film_actor', engine)
film_category_df = get_table_data('film_category', engine)
inventory_df = get_table_data('inventory',engine)
language_df = get_table_data('language',engine)
rental_df = get_table_data('rental',engine)
staff_df = get_table_data('staff',engine)
payment_df = get_table_data('payment',engine)
film_df = get_table_data('film',engine)

- Rampung semua dataframe dari Data Source 1, 2, dan 3 ke dalam sebuah **Dictionary**.
- Keys:
    - nama tabel
- Value:
    - dataframe

In [13]:
# Your code here
...

table_dict = {
#source 1
'city' : city_df,

#source 2
'country' : country_df,

#source 3
'actor' : actor_df, 
'store': store_df, 
'address' : address_df, 
'category' : category_df, 
'customer' : customer_df, 
'film_actor' : film_actor_df, 
'film_category' : film_category_df, 
'inventory' : inventory_df,
'language' : language_df,
'rental' : rental_df,
'staff' : staff_df,
'payment' : payment_df,
'film' : film_df
}

## 3. Data Validations

- Pada bagian ini akan dilakukan beberapa **pengecekan**, yaitu :
    - Check `Table Requirements`
    - Check Data `Shape`
    - Check `Columns`
    - Check Data `Types`
    - Check `Missing Values`
    - Check `Duplicates Data`

### 3.1. Check `Table Requirements`

- Pada bagian ini kita akan melakukan **pengecekan daftar tabel**.
- Pengecekan dilakukan pada :
    - Data Source I
    - Data Source II
    - Data Source III
- Pastikan tabel yang dimiliki dari data source sesuai dengan requirements table.

- Buat fungsi pengecekan Tabel : **check_table_requirements**
- Fungsi ini akan :
    - Memprint tabulate dengan header nama tabel dan hasil pengecekan tabel tersebut. ✓ jika tabelnya ada dan ✗ jika tabelnya tidak ada
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [14]:
# Your code here
...

def check_table_requirements(actual_table, requirements_table):
    print("STEP 1")

    actual_name = [table_name for table_name in actual_table]
    requirements_table_name = list(requirements_table.keys())
    is_exist = []

    for name in requirements_table_name:

        if name in actual_name:
            is_exist.append([name,'✓'])
        else:
            is_exist.append([name,'✗'])

    headerz = ['Table Name', "Is Exist"]
    table = tabulate(is_exist, headers=headerz, tablefmt="grid")
    print(table)

In [15]:
check_table_requirements(actual_table = table_dict, 
                         requirements_table = requirements_table)

STEP 1
+---------------+------------+
| Table Name    | Is Exist   |
+===============+============+
| actor         | ✓          |
+---------------+------------+
| store         | ✓          |
+---------------+------------+
| address       | ✓          |
+---------------+------------+
| category      | ✓          |
+---------------+------------+
| city          | ✓          |
+---------------+------------+
| country       | ✓          |
+---------------+------------+
| customer      | ✓          |
+---------------+------------+
| film_actor    | ✓          |
+---------------+------------+
| film_category | ✓          |
+---------------+------------+
| inventory     | ✓          |
+---------------+------------+
| language      | ✓          |
+---------------+------------+
| rental        | ✓          |
+---------------+------------+
| staff         | ✓          |
+---------------+------------+
| payment       | ✓          |
+---------------+------------+
| film          | ✓          |
+---------------+------------+

In [16]:
check_table_requirements(actual_table = table_dict, 
                         requirements_table = requirements_table)

STEP 1
+---------------+------------+
| Table Name    | Is Exist   |
+===============+============+
| actor         | ✓          |
+---------------+------------+
| store         | ✓          |
+---------------+------------+
| address       | ✓          |
+---------------+------------+
| category      | ✓          |
+---------------+------------+
| city          | ✓          |
+---------------+------------+
| country       | ✓          |
+---------------+------------+
| customer      | ✓          |
+---------------+------------+
| film_actor    | ✓          |
+---------------+------------+
| film_category | ✓          |
+---------------+------------+
| inventory     | ✓          |
+---------------+------------+
| language      | ✓          |
+---------------+------------+
| rental        | ✓          |
+---------------+------------+
| staff         | ✓          |
+---------------+------------+
| payment       | ✓          |
+---------------+------------+
| film          | ✓          |
+---------------+------------+

### 3.2. Check `Data Shape`

- Buat fungsi pengecekan data shape : **check_shape**
- Fungsi ini akan :
    - Memprint tabulate untuk menampilkan jumlah baris dan jumlah kolom dari setiap table.
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [17]:
# Your code here
...

def check_shape(actual_table):

    print("STEP 2")


    data_shape = []

    for table in actual_table:

        data_shape.append([table, actual_table[table].shape[0], actual_table[table].shape[1]] )


    head = ['Table_name', 'num of rows','num of column']
    table = tabulate(data_shape, headers=head, tablefmt="grid")

    print(table)

In [18]:
check_shape(actual_table = table_dict)

STEP 2
+---------------+---------------+-----------------+
| Table_name    |   num of rows |   num of column |
+===============+===============+=================+
| city          |           677 |               3 |
+---------------+---------------+-----------------+
| country       |           109 |               2 |
+---------------+---------------+-----------------+
| actor         |           200 |               4 |
+---------------+---------------+-----------------+
| store         |             2 |               4 |
+---------------+---------------+-----------------+
| address       |           603 |               8 |
+---------------+---------------+-----------------+
| category      |            16 |               3 |
+---------------+---------------+-----------------+
| customer      |           599 |              10 |
+---------------+---------------+-----------------+
| film_actor    |          5462 |               3 |
+---------------+---------------+-----------------+
| film_category |          1000 |               3 |
+---------------+---------------+-----------------+
| inventory     |          4581 |               4 |
+---------------+---------------+-----------------+
| language      |             6 |               3 |
+---------------+---------------+-----------------+
| rental        |         16044 |               7 |
+---------------+---------------+-----------------+
| staff         |             2 |              11 |
+---------------+---------------+-----------------+
| payment       |         14596 |               6 |
+---------------+---------------+-----------------+
| film          |          1000 |              13 |
+---------------+---------------+-----------------+

In [19]:
check_shape(actual_table = table_dict)

STEP 2
+---------------+---------------+-----------------+
| Table_name    |   num of rows |   num of column |
+===============+===============+=================+
| city          |           677 |               3 |
+---------------+---------------+-----------------+
| country       |           109 |               2 |
+---------------+---------------+-----------------+
| actor         |           200 |               4 |
+---------------+---------------+-----------------+
| store         |             2 |               4 |
+---------------+---------------+-----------------+
| address       |           603 |               8 |
+---------------+---------------+-----------------+
| category      |            16 |               3 |
+---------------+---------------+-----------------+
| customer      |           599 |              10 |
+---------------+---------------+-----------------+
| film_actor    |          5462 |               3 |
+---------------+---------------+-----------------+
| film_category |          1000 |               3 |
+---------------+---------------+-----------------+
| inventory     |          4581 |               4 |
+---------------+---------------+-----------------+
| language      |             6 |               3 |
+---------------+---------------+-----------------+
| rental        |         16044 |               7 |
+---------------+---------------+-----------------+
| staff         |             2 |              11 |
+---------------+---------------+-----------------+
| payment       |         14596 |               6 |
+---------------+---------------+-----------------+
| film          |          1000 |              13 |
+---------------+---------------+-----------------+

### 3.3. Check `Columns`

- Buat fungsi pengecekan nama-nama kolom pada setiap tabel : **check_columns**
- Fungsi ini akan :
    - Memprint tabulate untuk menampilkan tabel-tabel yang kolomnya tidak sesuai dengan requirements
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [20]:
# Your code here
...

def check_columns(actual_table, requirements_table):

    for table in requirements_table:

        checking_table = []

        print(f'Table : {table}')

        act_table_column = actual_table[table].columns.tolist()

        req_table_column = [item['column_name'] for item in requirements_table[table]]

        set_all = set(act_table_column) | set(req_table_column)

        for column_name in set_all:

            if column_name in act_table_column and column_name in req_table_column:
                checking_table.append([column_name, '✓', '✓'])
            elif column_name in act_table_column and column_name not in req_table_column:
                checking_table.append([column_name, '✓', '✗'])
            elif column_name not in act_table_column and column_name in req_table_column:
                checking_table.append([column_name, '✗', '✓'])
            
        headerz = ['Column Name', "Is Exist in Actual Table", "Is Exist in Requirements Table"]
        table = tabulate(checking_table, headers=headerz, tablefmt="grid")
        print(table)
        print("\n\n")
    

            


        # print(actual_table_colu)

In [21]:
check_columns(actual_table = table_dict,
              requirements_table = requirements_table)

Table : actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : store
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| address_id       | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| store_id         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| manager_staff_id | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+



Table : address
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| postal_code   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address2      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| phone         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| district      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : city
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✗                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country_id    | ✗                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country       | ✓                          | ✗                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : country
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country_id    | ✗                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : customer
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| activebool    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| create_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : inventory
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : language
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| language_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : rental
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| return_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : staff
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| password      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| username      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| picture       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : payment
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| payment_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| payment_date  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| amount        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| rental_rate      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| language_id      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| length           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| title            | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| special_features | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| release_year     | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| fulltext         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rating           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| description      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| replacement_cost | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rental_duration  | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| film_id          | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+

In [84]:
check_columns(actual_table = table_dict,
              requirements_table = requirements_table)

Table : actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : store
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| manager_staff_id | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| store_id         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| address_id       | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+



Table : address
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address2      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| district      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| postal_code   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| phone         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : city
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| city          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : country
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| country       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : customer
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| create_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| activebool    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : inventory
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : language
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| language_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : rental
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| return_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : staff
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| password      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| username      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| picture       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : payment
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| payment_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| payment_date  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| amount        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| rental_duration  | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| description      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| special_features | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| film_id          | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| title            | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| language_id      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rating           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rental_rate      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| fulltext         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| replacement_cost | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| length           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| release_year     | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+

### 3.4. Check `Data Types`

- Buat fungsi pengecekan nama-nama kolom pada setiap tabel : **check_data_types**
- Fungsi ini akan :
    - Memprint tabulate untuk menampilkan tabel dan kolom yang tipe datanya tidak sesuai dengan requirements
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [22]:
# Your code here
...

def check_data_types(actual_table, requirements_table):
    print("=> STEP 4: Check Data Types")
    summary_data = []

    for table_name, df in actual_table.items():
        if table_name in requirements_table:
            for column_info in requirements_table[table_name]:
                column_name = column_info["column_name"]
                requirements_type = column_info["data_type"]
                
                if column_name in df.columns:
                    actual_type = str(df[column_name].dtype)
                    match = "✔" if actual_type == requirements_type else "✘"
                    summary_data.append([table_name, column_name, actual_type, requirements_type, match])
                else:
                    summary_data.append([table_name, column_name, "N/A", requirements_type, "✘ (Column not found)"])

    headers = ["Table Name", "Column Name", "Actual Type", "Requirements Type", "Match"]

    mismatch_data = [row for row in summary_data if "✘" in row[4]]
    
    if mismatch_data:
        print("\nSummary of Mismatches Data Types:")
        print(tabulate(mismatch_data, headers = headers, tablefmt = "grid"))
    
    else:
        print("All Data Types Match")

In [23]:
check_data_types(actual_table = table_dict, 
                 requirements_table = requirements_table)

=> STEP 4: Check Data Types

Summary of Mismatches Data Types:
+--------------+---------------+---------------+---------------------+----------------------+
| Table Name   | Column Name   | Actual Type   | Requirements Type   | Match                |
+==============+===============+===============+=====================+======================+
| city         | country_id    | N/A           | int64               | ✘ (Column not found) |
+--------------+---------------+---------------+---------------------+----------------------+
| city         | last_update   | N/A           | datetime64[ns]      | ✘ (Column not found) |
+--------------+---------------+---------------+---------------------+----------------------+
| country      | country_id    | N/A           | int64               | ✘ (Column not found) |
+--------------+---------------+---------------+---------------------+----------------------+
| country      | last_update   | object        | datetime64[ns]      | ✘                    |
+--------------+---------------+---------------+---------------------+----------------------+
| customer     | create_date   | object        | datetime64[ns]      | ✘                    |
+--------------+---------------+---------------+---------------------+----------------------+

### 3.5. Check `Missing Values`

- Buat fungsi pengecekan nama-nama kolom pada setiap tabel : **check_missing_values**
- Fungsi ini akan :
    - Memprint tabulate untuk menampilkan tabel dan kolom yang mempunyai missing values. 
    - Menampilkan jumlah dan persentase missing values
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [24]:
# Your code here
...

def check_missing_values(actual_table):

    print("STEP 4")

    missing_value = []

    for table in actual_table:

        num_missing_value = actual_table[table].isna().sum().sum()

        missing_value.append([table, num_missing_value])

    headerz = ['Table Name', 'Num of Missing Value']
    table = tabulate(missing_value, headers=headerz, tablefmt="grid")
    print(table)

In [25]:
check_missing_values(actual_table = table_dict)

STEP 4
+---------------+------------------------+
| Table Name    |   Num of Missing Value |
+===============+========================+
| city          |                     17 |
+---------------+------------------------+
| country       |                      0 |
+---------------+------------------------+
| actor         |                      0 |
+---------------+------------------------+
| store         |                      0 |
+---------------+------------------------+
| address       |                      4 |
+---------------+------------------------+
| category      |                      0 |
+---------------+------------------------+
| customer      |                      0 |
+---------------+------------------------+
| film_actor    |                      0 |
+---------------+------------------------+
| film_category |                      0 |
+---------------+------------------------+
| inventory     |                      0 |
+---------------+------------------------+
| language      |                      0 |
+---------------+------------------------+
| rental        |                    183 |
+---------------+------------------------+
| staff         |                      1 |
+---------------+------------------------+
| payment       |                      0 |
+---------------+------------------------+
| film          |                      0 |
+---------------+------------------------+

### 3.6. Check `Duplicates Data`

- Buat fungsi pengecekan nama-nama kolom pada setiap tabel : **check_duplicates_data**
- Fungsi ini akan :
    - Memprint tabulate untuk menampilkan tabel yang mempunyai data duplikat. 
    - Menampilkan jumlah data yang duplikat (Semua data yang terindikasi duplikat). 
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
    - requirements_table : Requirements JSON
- Return : None

In [26]:
# Your code here
...

def check_duplicates_data(table_dict):
    
    print("=> STEP 6: Check Duplicates Data")
    duplicate_summary = []

    for table_name, df in table_dict.items():
        try:
            duplicate_rows = df[df.duplicated(keep = False)]
            
            if not duplicate_rows.empty:
                duplicate_summary.append([table_name, len(duplicate_rows)])
        except:
            pass

    if duplicate_summary:
        print("Duplicate Data Summary:")
        print(tabulate(duplicate_summary, headers=["Table Name", "Duplicate Rows Count"], tablefmt="grid"))
    else:
        print("No Duplicate Data Found")

In [27]:
check_duplicates_data(table_dict)

=> STEP 6: Check Duplicates Data
Duplicate Data Summary:
+--------------+------------------------+
| Table Name   |   Duplicate Rows Count |
+==============+========================+
| city         |                    154 |
+--------------+------------------------+

In [73]:
check_duplicates_data(table_dict)

=> STEP 6: Check Duplicates Data
Duplicate Data Summary:
+--------------+------------------------+
| Table Name   |   Duplicate Rows Count |
+==============+========================+
| city         |                    154 |
+--------------+------------------------+

## 4. Data Transform

- Proses transformasi ini dilakukan untuk **mempersiapkan data untuk diload ke Data Warehouse.**
- **Pertama, lakukanlah cleaning** sebelum datanya diload ke data warehouse **pada database dvdrental_clean**.
<center>

<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/10_01.png"/>
<center>

### 4.1. Data Cleansing

- Berdasarkan **hasil validations** diketahui bahwa data yang diperoleh dari beberapa data source **masih belum clean.**
    - **Kolom yang tidak sesuai requirements terdapat pada tabel:** 
	    - city
	    - country
    - **Terdapat missing values pada kolom :**
	    - address
	    - city
	    - rental
	    - staff
    - **Tipe data yang tidak sesuai requirements terdapat pada tabel :**
	    - city
	    - country
	    - customer
    - **Terdapat duplicates data pada kolom :**
	    - city

- Oleh karena itu, kita akan bersihkan datanya terlebih dahulu.

#### 4.1.1. Handle mismatch columns

**TABLE : country**

- Berikut adalah **data aktual** dari tabel "country"

In [28]:
country_df = table_dict['country']
country_df.head()

          country          last_update
0     Afghanistan  2006-02-15 09:44:00
1         Algeria  2006-02-15 09:44:00
2  American Samoa  2006-02-15 09:44:00
3          Angola  2006-02-15 09:44:00
4        Anguilla  2006-02-15 09:44:00

- Berikut adalah **requirements** untuk tabel "country"

In [29]:
requirements_table['country']

[{'column_name': 'country_id', 'data_type': 'int64'},
 {'column_name': 'last_update', 'data_type': 'datetime64[ns]'},
 {'column_name': 'country', 'data_type': 'object'}]

- Pada table country aktual belum mempunyai kolom country_id, maka :
    - **tambahkan colom country_id.**
- Ketentuan :
    - country_id tersebut dimulai dari angka 1 dan seterusnya

In [30]:
# Your code here
# Menambahkan kolom baru 'country_id' di posisi pertama
...
country_df.insert(0, 'country_id', range(1, len(country_df) + 1))


# Tampilkan 5 data teratas
...
country_df.head()

   country_id         country          last_update
0           1     Afghanistan  2006-02-15 09:44:00
1           2         Algeria  2006-02-15 09:44:00
2           3  American Samoa  2006-02-15 09:44:00
3           4          Angola  2006-02-15 09:44:00
4           5        Anguilla  2006-02-15 09:44:00

- **Rubah dataframe country pada table_dict**

In [31]:
# Your code here
...
table_dict['country'] = country_df

**TABLE : city**

- Berikut adalah **data aktual** pada tabel "city".

In [32]:
city_df = table_dict['city']

city_df.head()

   city_id                city               country
0        1  A Corua (La Corua)                 Spain
1        2                Abha          Saudi Arabia
2        3           Abu Dhabi  United Arab Emirates
3        4                Acua                Mexico
4        5               Adana                Turkey

- Berikut adalah **requirements** untuk table "city".

In [33]:
requirements_table['city']

[{'column_name': 'city_id', 'data_type': 'int64'},
 {'column_name': 'country_id', 'data_type': 'int64'},
 {'column_name': 'last_update', 'data_type': 'datetime64[ns]'},
 {'column_name': 'city', 'data_type': 'object'}]

- Pada tabel city :
    - **Buat kolom :**
        - country_id
        - last_update
    - **Hapus kolom :**
        - country
- Untuk mencapai tujuan tersebut, lakukan **merge dengan table country** untuk **mendapatkan data country_id dan last_update**.

In [34]:
# Your code here
...

temp_df = city_df.merge(country_df, left_on='country', right_on='country', how='left')

city_df = temp_df[['city_id', 'city', 'country_id',  'last_update']]

city_df.head()

   city_id                city  country_id          last_update
0        1  A Corua (La Corua)        87.0  2006-02-15 09:44:00
1        2                Abha        82.0  2006-02-15 09:44:00
2        3           Abu Dhabi       101.0  2006-02-15 09:44:00
3        4                Acua        60.0  2006-02-15 09:44:00
4        5               Adana        97.0  2006-02-15 09:44:00

- **Rubah dataframe city pada table_dict**

In [35]:
# Your code here
...
table_dict['city'] = city_df

- Setelah menyesuaikan kolom pada data aktual dengan requirements, **validasi** kolomnya kembali. Gunakan fungsi `check_columns`

In [36]:
check_columns(actual_table = table_dict,
              requirements_table = requirements_table)

Table : actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : store
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| address_id       | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| store_id         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| manager_staff_id | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+



Table : address
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| postal_code   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address2      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| phone         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| district      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : city
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| country_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| city_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : country
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| country       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : customer
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| activebool    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| create_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_actor
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| actor_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film_category
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| category_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : inventory
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| film_id       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : language
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| language_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| name          | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : rental
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| return_date   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| inventory_id  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : staff
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| active        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| first_name    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_name     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| store_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| password      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| email         | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| username      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| last_update   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| picture       | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| address_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : payment
+---------------+----------------------------+----------------------------------+
| Column Name   | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+===============+============================+==================================+
| payment_id    | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| staff_id      | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| rental_id     | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| customer_id   | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| payment_date  | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+
| amount        | ✓                          | ✓                                |
+---------------+----------------------------+----------------------------------+



Table : film
+------------------+----------------------------+----------------------------------+
| Column Name      | Is Exist in Actual Table   | Is Exist in Requirements Table   |
+==================+============================+==================================+
| rental_rate      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| last_update      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| language_id      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| length           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| title            | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| special_features | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| release_year     | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| fulltext         | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rating           | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| description      | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| replacement_cost | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| rental_duration  | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+
| film_id          | ✓                          | ✓                                |
+------------------+----------------------------+----------------------------------+

- Hal tersebut menunjukkan kolom-kolom pada data aktual sudah sesuai dengan requirements.

#### 4.1.2. Handle Missing Values

- Pada proses handle missing values ini akan dilakukan dropping missing values

- **Buatlah fungsi** untuk remove missing values : **remove_missing_values**
- Fungsi ini akan :
    - Menghapus missing values pada setiap tabel.
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
- Return :
    - cleaned_actual_table : Dictionary actual table yang sudah bersih dari missing values

In [37]:
# Your code here
...
def remove_missing_values(actual_table):

    for table in actual_table:

        actual_table[table] = actual_table[table].dropna()

    return actual_table

- Update table_dict dengan data yang sudah tidak mempunyai missing values

In [38]:
# Your code here
...

cleaned_table_dict = remove_missing_values(table_dict)

- Validasi missing valuenya kembali. Gunakan fungsi **check_missing_values**

In [39]:
check_missing_values(actual_table = cleaned_table_dict)

STEP 4
+---------------+------------------------+
| Table Name    |   Num of Missing Value |
+===============+========================+
| city          |                      0 |
+---------------+------------------------+
| country       |                      0 |
+---------------+------------------------+
| actor         |                      0 |
+---------------+------------------------+
| store         |                      0 |
+---------------+------------------------+
| address       |                      0 |
+---------------+------------------------+
| category      |                      0 |
+---------------+------------------------+
| customer      |                      0 |
+---------------+------------------------+
| film_actor    |                      0 |
+---------------+------------------------+
| film_category |                      0 |
+---------------+------------------------+
| inventory     |                      0 |
+---------------+------------------------+
| language      |                      0 |
+---------------+------------------------+
| rental        |                      0 |
+---------------+------------------------+
| staff         |                      0 |
+---------------+------------------------+
| payment       |                      0 |
+---------------+------------------------+
| film          |                      0 |
+---------------+------------------------+

- Dapat dilihat bahwa missing values sudah terhandle.

#### 4.1.3. Handle Data Types

- Pada proses handle data types akan dilakukan **casting tipe data** berdasarkan requirements yang telah diberikan.

- **Buatlah fungsi** untuk menghandle Data Types : **adjust_data_types**
- Fungsi ini akan :
    - Melakukan casting tipe data sesuai dengan requirements.
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
- Return :
    - cleaned_actual_table : Dictionary actual table yang sudah bersih dari missing values

In [40]:
# Your code here
...

def adjust_data_types(actual_table, requirements_table):
    print("=> STEP 7: Adjust Data Types")
    for table_name, df in actual_table.items():
        if table_name in requirements_table:
            for column_info in requirements_table[table_name]:
                column_name = column_info["column_name"]
                requirements_type = column_info["data_type"]
                
                if column_name in df.columns:
                    try:
                        if requirements_type == "int64":
                            actual_table[table_name][column_name] = actual_table[table_name][column_name].astype('int64')
                        elif requirements_type == "float64":
                            actual_table[table_name][column_name] = actual_table[table_name][column_name].astype('float64')
                        elif requirements_type == "object":
                            actual_table[table_name][column_name] = actual_table[table_name][column_name].astype('object')
                        elif requirements_type == "datetime64[ns]":
                            actual_table[table_name][column_name] = pd.to_datetime(actual_table[table_name][column_name])
                    except Exception as e:
                        print(f"Error converting {table_name}.{column_name} to {requirements_type}: {e}")

- Update table_dict dengan data yang sudah sesuai tipe datanya

In [41]:
# Your code here
...
cleaned_table_dict = adjust_data_types(cleaned_table_dict, requirements_table)

=> STEP 7: Adjust Data Types

- Validasi tipe data dari kolom pada setiap tabel. Gunakan fungsi **check_data_types**

In [42]:
check_data_types(actual_table =table_dict, 
                 requirements_table = requirements_table)

=> STEP 4: Check Data Types
All Data Types Match

- Dapat dilihat bahwa tipe data pada data aktual sudah sesuai.

#### 4.1.4. Handle Duplicates Data

- Pada proses handling data yang duplikat, akan dilakukan **drop data yang duplikat dengan mempertahankan record data yang pertama**.

- Buatlah fungsi untuk menghandle Data Types : **remove_duplicates**
- Fungsi ini akan :
    - Melakukan drop data yang duplikat dengan mempertahankan record data yang pertama.
- Parameter :
    - actual_table : Dictionary actual table (Data source 1, 2, 3)
- Return :
    - cleaned_table_dict : Dictionary actual table yang sudah bersih dari missing values

In [47]:
# Your code here
...
def remove_duplicates_data(table_dict):
    print("=> STEP 8: Remove Duplicates Data")
    for table_name, df in table_dict.items():
        print(f"Processing table: {table_name} with {len(df)} rows before removing duplicates.")
        table_dict[table_name] = df.drop_duplicates()

- Update table_dict dengan data yang sudah tidak mempunyai data duplikat

In [50]:
# Your code here
...
table_dict = remove_duplicates_data(table_dict)

=> STEP 8: Remove Duplicates Data
Processing table: city with 594 rows before removing duplicates.
Processing table: country with 109 rows before removing duplicates.
Processing table: actor with 200 rows before removing duplicates.
Processing table: store with 2 rows before removing duplicates.
Processing table: address with 599 rows before removing duplicates.
Processing table: category with 16 rows before removing duplicates.
Processing table: customer with 599 rows before removing duplicates.
Processing table: film_actor with 5462 rows before removing duplicates.
Processing table: film_category with 1000 rows before removing duplicates.
Processing table: inventory with 4581 rows before removing duplicates.
Processing table: language with 6 rows before removing duplicates.
Processing table: rental with 15861 rows before removing duplicates.
Processing table: staff with 1 rows before removing duplicates.
Processing table: payment with 14596 rows before removing duplicates.
Processing table: film with 1000 rows before removing duplicates.

TypeError: unhashable type: 'list'

- Validasi kembali data yang mengalami duplikat. Gunakan fungsi **check_duplicates_data**

In [51]:
check_duplicates_data(table_dict)

=> STEP 6: Check Duplicates Data
No Duplicate Data Found

### 4.2. Data Manipulation & Data Selection

- Pada bagian ini, kita akan coba **generate sebuah tabel** yang merupakan kombinasi dari beberapa tabel.
- Kita akan generate tabel `film_list`
- Tabel tersebut akan disimpan pada database **dvdrental_analysis**
- Tabel tersebut merupakan **kombinasi tabel :**
    - `actor`
    - `film_actor`
    - `film`
    - `film_category`
    - `category`
<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/10_02.png"/>

- Kolom-kolom yang akan kita **generate** adalah :
    - `fid` -> sama dengan film_id
    - `title` -> Judul film
    - `description` -> Deskripsi dari film
    - `category` -> Kategori film
    - `price` -> Harga film
    - `length` -> Durasi film
    - `rating` -> Rating film
    - `actors` -> Nama-nama aktor film tersebut

<center>
<img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/10_03.png"/>
<center>

- Pertama, **persiapkan dataframe yang diperlukan.**
- Dapatkan dataframenya dari **table_dict**

In [ ]:
# Your code here
...

- Gabungkan tabel-tabel yang diperlukan dengan melakukan **merge**.

- Merge : **Category -> film_category**
- on : **category_id**
- Join Type : **left join**
- Suffixes : ("_x1", "_y1")

In [54]:
# Your code here
# Buat dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df =  category_df.merge(film_category_df, left_on='category_id', right_on='category_id', how='left', suffixes=('_x1',"_y1"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

   category_id    name      last_update_x1  film_id      last_update_y1
0            1  Action 2006-02-15 09:46:27       19 2006-02-15 10:07:09
1            1  Action 2006-02-15 09:46:27       21 2006-02-15 10:07:09
2            1  Action 2006-02-15 09:46:27       29 2006-02-15 10:07:09
3            1  Action 2006-02-15 09:46:27       38 2006-02-15 10:07:09
4            1  Action 2006-02-15 09:46:27       56 2006-02-15 10:07:09

- Merge : **film_list -> film**
- on : **film_id**
- Join Type : **left join**
- Suffixes : ("_x2", "_y2")

In [57]:
film_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   film_id           1000 non-null   int64
 1   title             1000 non-null   object
 2   description       1000 non-null   object
 3   release_year      1000 non-null   int64
 4   language_id       1000 non-null   int64
 5   rental_duration   1000 non-null   int64
 6   rental_rate       1000 non-null   float64
 7   length            1000 non-null   int64
 8   replacement_cost  1000 non-null   float64
 9   rating            1000 non-null   object
 10  last_update       1000 non-null   datetime64[ns]
 11  special_features  1000 non-null   object
 12  fulltext          1000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(5), object(5)
memory usage: 101.7+ KB

In [56]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(film_df, left_on='film_id', right_on='film_id', how='left', suffixes=('_x2',"_y2"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...
1,1,Action,2006-02-15 09:46:27,21,2006-02-15 10:07:09,American Circus,A Insightful Drama of a Girl And a Astronaut w...,2006,1,3,4.99,129,17.99,R,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'administr':17 'american':1 'astronaut':11 'ci...
2,1,Action,2006-02-15 09:46:27,29,2006-02-15 10:07:09,Antitrust Tomatoes,A Fateful Yarn of a Womanizer And a Feminist w...,2006,1,5,2.99,168,11.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes]",'administr':17 'ancient':19 'antitrust':1 'dat...
3,1,Action,2006-02-15 09:46:27,38,2006-02-15 10:07:09,Ark Ridgemont,A Beautiful Yarn of a Pioneer And a Monkey who...,2006,1,6,0.99,68,25.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes, Behin...",'ark':1 'beauti':4 'desert':20 'explor':16 'mo...
4,1,Action,2006-02-15 09:46:27,56,2006-02-15 10:07:09,Barefoot Manchurian,A Intrepid Story of a Cat And a Student who mu...,2006,1,6,2.99,129,15.99,G,2013-05-26 14:50:58.951,"[Trailers, Commentaries]",'abandon':19 'amus':20 'barefoot':1 'cat':8 'g...

In [ ]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(film_df, left_on='film_id', right_on='film_id', how='left', suffixes=('_x2',"_y2"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...
1,1,Action,2006-02-15 09:46:27,21,2006-02-15 10:07:09,American Circus,A Insightful Drama of a Girl And a Astronaut w...,2006,1,3,4.99,129,17.99,R,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'administr':17 'american':1 'astronaut':11 'ci...
2,1,Action,2006-02-15 09:46:27,29,2006-02-15 10:07:09,Antitrust Tomatoes,A Fateful Yarn of a Womanizer And a Feminist w...,2006,1,5,2.99,168,11.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes]",'administr':17 'ancient':19 'antitrust':1 'dat...
3,1,Action,2006-02-15 09:46:27,38,2006-02-15 10:07:09,Ark Ridgemont,A Beautiful Yarn of a Pioneer And a Monkey who...,2006,1,6,0.99,68,25.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes, Behin...",'ark':1 'beauti':4 'desert':20 'explor':16 'mo...
4,1,Action,2006-02-15 09:46:27,56,2006-02-15 10:07:09,Barefoot Manchurian,A Intrepid Story of a Cat And a Student who mu...,2006,1,6,2.99,129,15.99,G,2013-05-26 14:50:58.951,"[Trailers, Commentaries]",'abandon':19 'amus':20 'barefoot':1 'cat':8 'g...

- Merge : **film_list -> film_actor**
- on : **film_id**
- Join Type : **inner join**
- Suffixes : ("_x3", "_y3")

In [58]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(film_actor_df, left_on='film_id', right_on='film_id', how='inner', suffixes=('_x3',"_y3"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update_x3,special_features,fulltext,actor_id,last_update_y3
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,5,2006-02-15 10:05:03
1,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,27,2006-02-15 10:05:03
2,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,37,2006-02-15 10:05:03
3,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,43,2006-02-15 10:05:03
4,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,84,2006-02-15 10:05:03

In [ ]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(film_actor_df, left_on='film_id', right_on='film_id', how='inner', suffixes=('_x3',"_y3"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update_x3,special_features,fulltext,actor_id,last_update_y3
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,5,2006-02-15 10:05:03
1,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,27,2006-02-15 10:05:03
2,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,37,2006-02-15 10:05:03
3,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,43,2006-02-15 10:05:03
4,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,84,2006-02-15 10:05:03

- Merge : **film_list -> actor**
- on : **actor_id**
- Join Type : **inner join**
- Suffixes : ("_x4", "_y4")

In [59]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(actor_df, left_on='actor_id', right_on='actor_id', how='inner', suffixes=('_x4',"_y4"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,...,replacement_cost,rating,last_update_x3,special_features,fulltext,actor_id,last_update_y3,first_name,last_name,last_update
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,5,2006-02-15 10:05:03,Johnny,Lollobrigida,2013-05-26 14:47:57.620
1,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,27,2006-02-15 10:05:03,Julia,Mcqueen,2013-05-26 14:47:57.620
2,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,37,2006-02-15 10:05:03,Val,Bolger,2013-05-26 14:47:57.620
3,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,43,2006-02-15 10:05:03,Kirk,Jovovich,2013-05-26 14:47:57.620
4,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,84,2006-02-15 10:05:03,James,Pitt,2013-05-26 14:47:57.620

In [ ]:
# Your code here
# Update dataframe "film_list" untuk menyimpan hasil merge
...
film_list_df = film_list_df.merge(actor_df, left_on='actor_id', right_on='actor_id', how='inner', suffixes=('_x4',"_y4"))

# Tampilkan 5 data "film_list" teratas
...
film_list_df.head()

,category_id,name,last_update_x1,film_id,last_update_y1,title,description,release_year,language_id,rental_duration,...,replacement_cost,rating,last_update_x3,special_features,fulltext,actor_id,last_update_y3,first_name,last_name,last_update
0,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,5,2006-02-15 10:05:03,Johnny,Lollobrigida,2013-05-26 14:47:57.620
1,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,27,2006-02-15 10:05:03,Julia,Mcqueen,2013-05-26 14:47:57.620
2,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,37,2006-02-15 10:05:03,Val,Bolger,2013-05-26 14:47:57.620
3,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,43,2006-02-15 10:05:03,Kirk,Jovovich,2013-05-26 14:47:57.620
4,1,Action,2006-02-15 09:46:27,19,2006-02-15 10:07:09,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,...,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...,84,2006-02-15 10:05:03,James,Pitt,2013-05-26 14:47:57.620

- Selanjutnya, **gabungkan** `first_name` dan `last_name` menjadi `full_name`

In [60]:
# Gabungkan nama depan dan belakang aktor
...
film_list_df['full_name'] = film_list_df['first_name'] + ' ' + film_list_df['last_name']

# Tampilkan kolom "full_name"
...
film_list_df['full_name'].head()

0    Johnny Lollobrigida
1          Julia Mcqueen
2             Val Bolger
3          Kirk Jovovich
4             James Pitt
Name: full_name, dtype: object

- Perlu diketahui bahwa satu film bisa terdiri dari beberapa aktor.
- Oleh karena itu, **gabung nama-nama aktor tersebut di satu film yang sama**.
- Contoh :
    <center>
    <img src="https://sekolahdata-assets.s3.ap-southeast-1.amazonaws.com/notebook-images/mde-intro-to-data-eng/10_04.png"/>
    <center>

In [61]:
film_list_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5462 entries, 0 to 5461
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   category_id       5462 non-null   int64
 1   name              5462 non-null   object
 2   last_update_x1    5462 non-null   datetime64[ns]
 3   film_id           5462 non-null   int64
 4   last_update_y1    5462 non-null   datetime64[ns]
 5   title             5462 non-null   object
 6   description       5462 non-null   object
 7   release_year      5462 non-null   int64
 8   language_id       5462 non-null   int64
 9   rental_duration   5462 non-null   int64
 10  rental_rate       5462 non-null   float64
 11  length            5462 non-null   int64
 12  replacement_cost  5462 non-null   float64
 13  rating            5462 non-null   object
 14  last_update_x3    5462 non-null   datetime64[ns]
 15  special_features  5462 non-null   object
 16  fulltext          5462 non-null   object
 17  actor_id          5462 non-null   int64
 18  last_update_y3    5462 non-null   datetime64[ns]
 19  first_name        5462 non-null   object
 20  last_name         5462 non-null   object
 21  last_update       5462 non-null   datetime64[ns]
 22  full_name         5462 non-null   object
dtypes: datetime64[ns](5), float64(2), int64(7), object(9)
memory usage: 981.6+ KB

In [62]:
# Your code here
# Gabungkan nama aktor menjadi satu string untuk setiap film
...
film_list_df = film_list_df.groupby(['film_id', 'title', 'description', 'name', 'rental_rate', 'length', 'rating'])['full_name'].apply(lambda x: ', '.join(x))

# Tampilkan 5 data teratas
...
film_list_df.head()

film_id  title             description                                                                                                            name         rental_rate  length  rating
1        Academy Dinosaur  A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies                       Documentary  0.99         86      PG        Penelope Guiness, Christian Gable, Lucille Tra...
2        Ace Goldfinger    A Astounding Epistle of a Database Administrator And a Explorer who must Find a Car in Ancient China                   Horror       4.99         48      G         Bob Fawcett, Minnie Zellweger, Sean Guiness, C...
3        Adaptation Holes  A Astounding Reflection of a Lumberjack And a Car who must Sink a Lumberjack in A Baloon Factory                       Documentary  2.99         50      NC-17     Nick Wahlberg, Bob Fawcett, Cameron Streep, Ra...
4        Affair Prejudice  A Fanciful Documentary of a Frisbee And a Lumberjack who must Chase a Monkey in A Shark Tank                           Horror       2.99         117     G         Jodie Degeneres, Scarlett Damon, Kenneth Pesci...
5        African Egg       A Fast-Paced Documentary of a Pastry Chef And a Dentist who must Pursue a Forensic Psychologist in The Gulf of Mexico  Family       2.99         130     G         Gary Phoenix, Dustin Tautou, Matthew Leigh, Ma...
Name: full_name, dtype: object

- Hasil tersebut **masih berupa "series"**
- Oleh karena itu, **rubah menjadi dataframe**

In [65]:
# Your code here
# Rubah dari series menjadi dataframe
...
film_list_df = pd.DataFrame(film_list_df).reset_index()

# Tampilkan 5 data teratas
...
film_list_df.head()

,film_id,title,description,name,rental_rate,length,rating,full_name
0,1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,0.99,86,PG,"Penelope Guiness, Christian Gable, Lucille Tra..."
1,2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,Horror,4.99,48,G,"Bob Fawcett, Minnie Zellweger, Sean Guiness, C..."
2,3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"Nick Wahlberg, Bob Fawcett, Cameron Streep, Ra..."
3,4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"Jodie Degeneres, Scarlett Damon, Kenneth Pesci..."
4,5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"Gary Phoenix, Dustin Tautou, Matthew Leigh, Ma..."

In [69]:
film_list_df.columns

Index(['film_id', 'title', 'description', 'name', 'rental_rate', 'length',
       'rating', 'full_name'],
      dtype='object')

- Dapat dilihat, yang berstatus sebagai "kolom" hanya "full_name", selebihnya masih berupa index.
- Oleh karena itu, lakukan **reset index**

In [70]:
# Your code here
# Reset index
...
film_list_df = film_list_df.reset_index(drop=True)

# Tampilkan 5 data teratas
...
film_list_df.head()

,film_id,title,description,name,rental_rate,length,rating,full_name
0,1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,0.99,86,PG,"Penelope Guiness, Christian Gable, Lucille Tra..."
1,2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,Horror,4.99,48,G,"Bob Fawcett, Minnie Zellweger, Sean Guiness, C..."
2,3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"Nick Wahlberg, Bob Fawcett, Cameron Streep, Ra..."
3,4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"Jodie Degeneres, Scarlett Damon, Kenneth Pesci..."
4,5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"Gary Phoenix, Dustin Tautou, Matthew Leigh, Ma..."

- Terakhir, **rubah nama kolom**.
    - `film_id` : `fid`
    - `name` : `category`
    - `rental_rate` : `price`
    - `full_name` : `actors`

In [71]:
# Your code here
# Buat mapping perubahan nama kolom
...
mapping = {
    'film_id':'fid',
    'name' : 'category',
    'rental_rate': 'price',
    'full_name': 'actors'
}

In [72]:
# Your code here
# Rubah nama kolom
...
film_list_df = film_list_df.rename(columns=mapping)

# Tampilkan 5 data teratas
...
film_list_df.head()

,fid,title,description,category,price,length,rating,actors
0,1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,Documentary,0.99,86,PG,"Penelope Guiness, Christian Gable, Lucille Tra..."
1,2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,Horror,4.99,48,G,"Bob Fawcett, Minnie Zellweger, Sean Guiness, C..."
2,3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,Documentary,2.99,50,NC-17,"Nick Wahlberg, Bob Fawcett, Cameron Streep, Ra..."
3,4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,Horror,2.99,117,G,"Jodie Degeneres, Scarlett Damon, Kenneth Pesci..."
4,5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,Family,2.99,130,G,"Gary Phoenix, Dustin Tautou, Matthew Leigh, Ma..."

## 5. Load Data To Data Warehouse

- ***NOTES : Pastikan anda sudah mempersiapkan Data Warehousenya. Silahkan lihat "Live Class Preparation" pada Chapter 9***

### 5.1. Setup Connection

- Buat fungsi untuk membuat engine postgres.
    - user = "root"
    - password = "qwerty123"
    - host = "localhost"
    - port = "3000"
- Parameter : Nama database

In [76]:
# Your code here
...
def dw_postgres_engine(dbname):

    user = 'root'
    password = 'qwerty123'
    host = 'localhost'
    port = '3000'

    engine = create_engine(f'postgresql://{user}:{password}@{host}:{port}/{dbname}')

    return engine

### 5.2. Load to "dvdrental_clean" Database

#### 5.2.1. Create table

- Buatlah table untuk database tersebut.
- Gunakan schema berikut :
    ```sql
    -- Membuat skema public jika belum ada
    CREATE SCHEMA IF NOT EXISTS public;

    -- Buat tabel
    CREATE TABLE public.actor (
        actor_id SERIAL PRIMARY KEY,
        last_update TIMESTAMP,
        first_name VARCHAR,
        last_name VARCHAR
    );

    CREATE TABLE public.store (
        store_id SERIAL PRIMARY KEY,
        manager_staff_id INTEGER,
        address_id INTEGER,
        last_update TIMESTAMP
    );

    CREATE TABLE public.address (
        last_update TIMESTAMP,
        city_id INTEGER,
        address_id SERIAL PRIMARY KEY,
        district VARCHAR,
        phone VARCHAR,
        postal_code VARCHAR,
        address VARCHAR,
        address2 VARCHAR
    );

    CREATE TABLE public.category (
        category_id SERIAL PRIMARY KEY,
        last_update TIMESTAMP,
        name VARCHAR
    );

    CREATE TABLE public.city (
        city_id SERIAL PRIMARY KEY,
        country_id INTEGER,
        last_update TIMESTAMP,
        city VARCHAR
    );

    CREATE TABLE public.country (
        country_id SERIAL PRIMARY KEY,
        last_update TIMESTAMP,
        country VARCHAR
    );

    CREATE TABLE public.customer (
        active INTEGER,
        store_id INTEGER,
        create_date TIMESTAMP,
        last_update TIMESTAMP,
        customer_id SERIAL PRIMARY KEY,
        address_id INTEGER,
        activebool BOOLEAN,
        first_name VARCHAR,
        last_name VARCHAR,
        email VARCHAR
    );

    CREATE TABLE public.film_actor (
        actor_id SERIAL PRIMARY KEY,
        film_id INTEGER,
        last_update TIMESTAMP
    );

    CREATE TABLE public.film_category (
        film_id SERIAL PRIMARY KEY,
        category_id INTEGER,
        last_update TIMESTAMP
    );

    CREATE TABLE public.inventory (
        inventory_id SERIAL PRIMARY KEY,
        film_id INTEGER,
        store_id INTEGER,
        last_update TIMESTAMP
    );

    CREATE TABLE public.language (
        language_id SERIAL PRIMARY KEY,
        last_update TIMESTAMP,
        name VARCHAR
    );

    CREATE TABLE public.rental (
        rental_id SERIAL PRIMARY KEY,
        rental_date TIMESTAMP,
        inventory_id INTEGER,
        customer_id INTEGER,
        return_date TIMESTAMP,
        staff_id INTEGER,
        last_update TIMESTAMP
    );

    CREATE TABLE public.staff (
        picture VARCHAR,
        address_id INTEGER,
        store_id INTEGER,
        active BOOLEAN,
        last_update TIMESTAMP,
        staff_id SERIAL PRIMARY KEY,
        first_name VARCHAR,
        last_name VARCHAR,
        password VARCHAR,
        email VARCHAR,
        username VARCHAR
    );

    CREATE TABLE public.payment (
        payment_id SERIAL PRIMARY KEY,
        customer_id INTEGER,
        staff_id INTEGER,
        rental_id INTEGER,
        amount FLOAT,
        payment_date TIMESTAMP
    );

    CREATE TABLE public.film (
        fulltext VARCHAR,
        rating VARCHAR,
        last_update TIMESTAMP,
        film_id SERIAL PRIMARY KEY,
        release_year INTEGER,
        language_id INTEGER,
        rental_duration INTEGER,
        rental_rate FLOAT,
        length INTEGER,
        replacement_cost FLOAT,
        title VARCHAR,
        description VARCHAR,
        special_features VARCHAR
    );
    ```

#### 5.2.2. Load Data

- Lakukan load data ke "dvdrental_analysis" database

In [77]:
# Your code here
...
dw_engine = dw_postgres_engine('dvdrental_clean')

for table_name, df in table_dict.items():
    try:
        df.to_sql(table_name, dw_engine, if_exists='replace', index=False)
        print(f"Table '{table_name}' has been successfully written to the database.")
    except Exception as e:
        print(f"Error writing table '{table_name}' to the database: {e}")

dw_engine.dispose()

Table 'city' has been successfully written to the database.
Table 'country' has been successfully written to the database.
Table 'actor' has been successfully written to the database.
Table 'store' has been successfully written to the database.
Table 'address' has been successfully written to the database.
Table 'category' has been successfully written to the database.
Table 'customer' has been successfully written to the database.
Table 'film_actor' has been successfully written to the database.
Table 'film_category' has been successfully written to the database.
Table 'inventory' has been successfully written to the database.
Table 'language' has been successfully written to the database.
Table 'rental' has been successfully written to the database.
Table 'staff' has been successfully written to the database.
Table 'payment' has been successfully written to the database.
Table 'film' has been successfully written to the database.

### 5.3. Load to "dvdrental_analysis" Database

#### 5.3.1. Create Table

- Buatlah table untuk database tersebut.
- Gunakan schema berikut :
    ```sql
    -- Membuat skema public jika belum ada
    CREATE SCHEMA IF NOT EXISTS public;

    -- Membuat tabel film_list
    CREATE TABLE public.film_list (
        fid SERIAL PRIMARY KEY,
        title VARCHAR,
        description VARCHAR,
        category VARCHAR,
        price FLOAT,
        length INTEGER,
        rating VARCHAR,
        actors VARCHAR
    );
    ```

#### 5.3.2. Load Data

- Lakukan load data ke "dvdrental_analysis" database

In [78]:
# Your code here
# Buat engine postgres
...

dw_engine = dw_postgres_engine('dvdrental_analysis')

# Insert data ke table film_list
film_list_df.to_sql('film_list', dw_engine, if_exists='replace', index=False)

# Tutup koneksi ke database
dw_engine.dispose()

Untuk code dalam bentuk Python script, ada di https://github.com/rahilpacmann/case-data-wrangling